### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by sixhobbits** [webdigi/AWS-AMI-Automated-Creation-Deletion#5]
I followed all of the instructions, but the AMI wasn't made. In the lambda logs I see this error (for the create script)

```
Syntax error in module 'index': SyntaxError
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
```

The only thing I changed in the script was the region.

**Comment by sixhobbits** [comment]
There was an extra line at the bottom of the script. I'll drink more coffee before opening an issue next time.
